{{- if and .Values.fluentbit.enabled .Values.fluentbit.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "loki-stack.fluentbit.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "loki-stack.fluentbit.labels" . | nindent 4 }}
{{- end }}
