{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "loki-stack.fullname" . }}-loki
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  labels:
    {{- include "loki-stack.loki.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki-stack.loki.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http-metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
{{- end }}
