{{- if .Values.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus-stack.fullname" . }}-prometheus
  labels:
    {{- include "prometheus-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prometheus-stack.fullname" . }}-prometheus
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus-stack.fullname" . }}-prometheus
  namespace: {{ .Values.global.namespace }}
---
{{- end }}
{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus-stack.fullname" . }}-kube-state-metrics
  labels:
    {{- include "prometheus-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prometheus-stack.fullname" . }}-kube-state-metrics
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus-stack.fullname" . }}-kube-state-metrics
  namespace: {{ .Values.global.namespace }}
{{- end }}
