{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-stack.fullname" . }}-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "prometheus-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
---
{{- end }}
{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-stack.fullname" . }}-kube-state-metrics
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "prometheus-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-state-metrics
---
{{- end }}
{{- if .Values.nodeExporter.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-stack.fullname" . }}-node-exporter
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "prometheus-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
{{- end }}
