{{- if and .Values.fluentbit.enabled .Values.fluentbit.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "loki-stack.fullname" . }}-fluent-bit-read
  labels:
    {{- include "loki-stack.fluentbit.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  - nodes/proxy
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "loki-stack.fullname" . }}-fluent-bit-read
  labels:
    {{- include "loki-stack.fluentbit.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "loki-stack.fullname" . }}-fluent-bit-read
subjects:
- kind: ServiceAccount
  name: {{ include "loki-stack.fluentbit.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
