{{- if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki-stack.fullname" . }}-loki
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "loki-stack.loki.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "loki-stack.loki.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "loki-stack.loki.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
      - name: loki
        image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
        imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
        args:
          - -config.file=/etc/loki/loki.yaml
        ports:
        - name: http-metrics
          containerPort: {{ .Values.loki.config.server.http_listen_port }}
          protocol: TCP
        - name: grpc
          containerPort: {{ .Values.loki.config.server.grpc_listen_port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          {{- toYaml .Values.loki.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /loki
        env:
        - name: JAEGER_AGENT_HOST
          value: ""
        - name: JAEGER_ENDPOINT
          value: ""
        - name: JAEGER_SAMPLER_TYPE
          value: ""
        - name: JAEGER_SAMPLER_PARAM
          value: ""
      volumes:
      - name: config
        configMap:
          name: {{ include "loki-stack.fullname" . }}-loki-config
      - name: storage
        {{- if .Values.loki.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "loki-stack.fullname" . }}-loki-storage
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
