{{- if .Values.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana-stack.fullname" . }}-alertmanager
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "grafana-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/alertmanager-configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "grafana-stack.alertmanager.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alertmanager
  template:
    metadata:
      labels:
        {{- include "grafana-stack.alertmanager.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/alertmanager-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
          args:
            - --config.file=/etc/alertmanager/config.yml
            - --storage.path=/alertmanager
            - --web.external-url=http://localhost:9093/
            - --web.route-prefix=/
            - --cluster.listen-address=
            - --log.level=info
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: storage
              mountPath: /alertmanager
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.alertmanager.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "grafana-stack.fullname" . }}-alertmanager-config
        - name: storage
        {{- if .Values.alertmanager.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "grafana-stack.fullname" . }}-alertmanager-pvc
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.alertmanager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alertmanager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alertmanager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
