apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana-stack.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "grafana-stack.labels" . | nindent 4 }}
automountServiceAccountToken: true
