{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-stack.fullname" . }}-kube-state-metrics
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "prometheus-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prometheus-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kube-state-metrics
  template:
    metadata:
      labels:
        {{- include "prometheus-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kube-state-metrics
    spec:
      serviceAccountName: {{ include "prometheus-stack.fullname" . }}-kube-state-metrics
      securityContext:
        {{- toYaml .Values.kubeStateMetrics.securityContext | nindent 8 }}
      containers:
      - name: kube-state-metrics
        image: "{{ .Values.kubeStateMetrics.image.repository }}:{{ .Values.kubeStateMetrics.image.tag }}"
        imagePullPolicy: {{ .Values.kubeStateMetrics.image.pullPolicy }}
        args:
          - --port=8080
          - --telemetry-port=8081
          - --resources=certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
        ports:
        - name: http-metrics
          containerPort: 8080
          protocol: TCP
        - name: telemetry
          containerPort: 8081
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-metrics
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http-metrics
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.kubeStateMetrics.resources | nindent 10 }}
      {{- with .Values.kubeStateMetrics.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeStateMetrics.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeStateMetrics.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
