apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "grafana-stack.fullname" . }}-fluent-bit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: fluent-bit
spec:
  selector:
    matchLabels:
      {{- include "grafana-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: fluent-bit
  template:
    metadata:
      labels:
        {{- include "grafana-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: fluent-bit
    spec:
      serviceAccountName: {{ include "grafana-stack.fullname" . }}-fluent-bit
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:2.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
          name: http
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: pos-db
          mountPath: /fluent-bit/tail
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: FLUENT_CONF
          value: fluent-bit.conf
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: {{ include "grafana-stack.fullname" . }}-fluent-bit-config
      - name: pos-db
        emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana-stack.fullname" . }}-fluent-bit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-stack.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grafana-stack.fullname" . }}-fluent-bit-read
  labels:
    {{- include "grafana-stack.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "grafana-stack.fullname" . }}-fluent-bit-read
  labels:
    {{- include "grafana-stack.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "grafana-stack.fullname" . }}-fluent-bit-read
subjects:
- kind: ServiceAccount
  name: {{ include "grafana-stack.fullname" . }}-fluent-bit
  namespace: {{ .Release.Namespace }}
