apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-stack.fullname" . }}-fluent-bit-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-stack.labels" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /var/log/containers/*enhanced-test-app*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  1
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        DB                /var/log/flb_kube.db
        DB.Sync           Normal

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On

    [FILTER]
        Name         parser
        Match        kube.*
        Key_Name     log
        Parser       json_parser
        Reserve_Data On
        Preserve_Key On

    [FILTER]
        Name         modify
        Match        kube.*
        Add          cluster local
        Add          source fluent-bit

    [OUTPUT]
        Name            loki
        Match           *
        Host            loki.observability.svc.cluster.local
        Port            3100
        Labels          job=fluent-bit,service=enhanced-test-app,cluster=local
        Label_keys      $kubernetes['namespace_name'],$kubernetes['pod_name'],$kubernetes['container_name'],$level,$trace_id,$endpoint,$method,$status_code
        Remove_keys     kubernetes,stream,time
        Line_format     json
        Auto_kubernetes_labels On

  parsers.conf: |
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On
        Decode_Field_As escaped_utf8 log

    [PARSER]
        Name        json_parser
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%fZ
        Time_Keep   On
